model:
  model: azure/gpt-5.5-20260424 # please follow litellm name format
  base_url: your_base_url
  api_key: your_api_key
  max_output_tokens: 100000
  # other litellm args

agent:
  max_iterations: 100
  timeout: 300 # minute
  num_workers: 2
  workspace: docker
  output_dir: logs
  tool_preset: default
  enable_condenser: true
  condenser_max_size: 240
  condenser_keep_first: 2
